# Cloncluciones y recomendaciones



## Cloncluciones [@xie2015]

De acuerdo a los resultados generados, mediante la prueba de hipótesis de T-student con
un nivel de confianza de 95% y una significancia de 5 %, justificando la implicación de la
**geometría fractal** en la composición plástica tridimensional, se obtienen las conclusiones:

1. Al 95% de confianza se verifica que $\rho=0.00<\alpha=0.05$ por lo tanto la aplicación
de la geometría fractal mejora significativamente la variedad en la composición
plástica tridimensional de los estudiantes. Es decir el estudiante es capaz de varíar
caracteristicas físicas, mostrar contrastes en los elementos y varíar la distribución
de los elementos.

2. Al 95% de confianza se verifica que $\rho=0.00<\alpha=0.05$ por lo tanto la aplicación de la
**geometría fractal** mejora positivamente la **unidad** en la composición
plástica tridimensional de los estudiantes. *Es decir el estudiante es capaz de  unificar caracteristicas
físicas, unificar elementos plásticos y generar un sistema estructural*.

3. Al 95% de confianza se verifica que $\rho=0.00<\alpha=0.05$ por lo tanto la aplicación
de la **geometría fractal** mejora significantemente el **ritmo** en la composición plástica
tridimensional de los estudiantes. *Es decir el estudiante es capaz de representar ritmo progresivo,
representar ritmo aleatorio regresivo, mostrar ritmo regular (constante) y representar
ritmo mixto*.

4. Al 95% de confianza se verifica que $\rho=0.00<\alpha=0.05$ por lo tanto la aplicación de
la **geometría fractal** desarrolla significativamente el **equilibrio** en la composición plástica
tridimensional tridimensional de los estudiantes. *Es decir el estudiante es capaz de equilibrar
centro de gravedad, equilibrar elementos plásticos y equilibrar tensión*.

5. Al 95% de confianza se verifica que $\rho=0.00<\alpha=0.05$ por lo tanto la aplicación de la
**geometría fractal** desarrolla significativamente el **énfasis** en la composición plástica tridimensional
tridimensional de los estudiantes. *Es decir el estudiante es capaz de manifestar punto
focal en formas, representar punto focal en color y exponer punto focal en texturas*.

6. Con un nivel de confianza del 95 %, se observa que $\rho=0.00<\alpha=0.05$, lo que indica
rechazar la hipótesis nula y aceptar la hipótesis alterna, entonces, la aplicación de la
**geometría fractal** influye significativamente en el desarrollo de la **composición plástica
tridimensional** de los estudiantes de la Escuela de Formación Profesional de Ingenieria
Civil UNSCH 2019. *Es decir el estudiante desarrolla la capacidad de aplicar la variedad,
la unidad, el ritmo, el equilibrio y el equilibrio correctamente en la composición
plástica tridimensional*.

## Recomendaciones


De acuerdo a los resultados de la investigación y a la necesidad de colaborar, con estrategias
didácticas en la enseñanza de la composición plástica tridimensional en el campo educativo,
me permito recomendar:

1. A las **autoridades universitarias** a fin de implementar en la reglamentación de los términos
de referencia, sobre la **geometría fractal** para contribuir a la solución de los problemas
de la enseñanza y aprendizaje, en la comunidad universitaria.

2. A las **autoridades de la facultad de ingeniería minas, geología y civil UNSCH** y sus correspondientes
escuelas profesionales, a fin de **implementar en los planes curriculares**,
nuevas asignaturas que permitan orientar la formación profesional de los estudiantes,
que involucren el desarrollo de las siguientes los siguientes principios de la composición: variedad,
unidad, ritmo y equilibrio; para coadyuvar en la solución de los problemas compositivos,
en la comunidad local, regional y nacional.

3. A los **docentes y estudiantes de la Escuela de Formación Profesional de Ingeniería
Civil UNSCH – Ayacucho**, a fin de poner en práctica la **geometría fractal**.
